#!/bin/sh
# autogenerated by /home/mastar/.config/awesome/massh/bin/w_autostart.sh at 20120723.183244
# test : MAS_WMCTRL='/usr/bin/wmctrl'



### ! type -t m_echo >/dev/null 2>&1 && [ -f $MAS_BIN/runonce/tools.sh  ] && . $MAS_BIN/runonce/tools.sh

#mas_notify2_t "running ${BASH_SOURCE[0]}" >/dev/null 2>&1

export MAS_NV_VERSION='295.59'
export MAS_KRN_VERSION='3.0.26-tuxonice.120608.m.g'
export MAS_WM_SHLVL='2'
export MAS_WM_UPTIME0=' 18:32:45 up 2 days, 10:26,  1 user,  load average: 1.15, 0.91, 0.55'
export MAS_PREV_WM_STATUS='quit'
export MAS_PREV_WM_TIME='20120723.183245'
export MAS_WM_QUIT_COUNT='91'
# export MAS_WM_RESTART_COUNT='0'
export MAS_WM_CONFIGDIR='/home/mastar/.config/awesome'
export MAS_WM_STATUSDIR='/home/mastar/.config/awesome/massh/current'
export MAS_PROFILE_READ=';/home/mastar/.profile:20120723.183238'
export MAS_BASHRC_READ=';/home/mastar/.bashrc:20120723.183238'
export MAS_WM='awesome'
export MAS_WM_STAT_DIR='/home/mastar/hw/wm/awesome/stat'
# export
# export
