#!/bin/sh
echo "sb.$PPID.$$.$LINENO ($STY) date:`date +'%s.%N'`" >>"/tmp/mscreen.log"
export MAS_RSC="$MAS_RSC;screen_bash:$LINENO($STY)"


echo "sb.$$.$LINENO ($STY) date:`date +'%s.%N'`" >>"/tmp/mscreen.log"

echo "sb.$$.$LINENO ($STY) date:`date +'%s.%N'`" >>"/tmp/mscreen.log"
[[ -r "$MAS_BASH_FUNCTIONS" ]] && . $MAS_BASH_FUNCTIONS
$MAS_LOGGER "running ${BASH_ARGV[0]}"

#set > /tmp/screen_bash.$UID.set.txt
$MAS_LOGGER screen_bash :TERM:: "$TERM"
$MAS_LOGGER screen_bash :STY:: "$STY"
#$MAS_LOGGER screen_bash :A:: "$@"
#$MAS_LOGGER screen_bash :B:: "$*"
export MAS_RSC="$MAS_RSC;screen_bash:$LINENO($STY)"


echo "sb.$$.$LINENO ($STY) date:`date +'%s.%N'`" >>"/tmp/mscreen.log"
if [ -n "$STY" ] ; then
  MAS_STY_TAIL=`echo $STY | ${MAS_SED_CMD:=/bin/sed} 's/\([0-9]\+\)\./'/`
  $MAS_LOGGER "1. MAS_STY_TAIL=$MAS_STY_TAIL"
  [[ -n "$MAS_PNAME" ]] || export MAS_PNAME=`echo $MAS_STY_TAIL | ${MAS_SED_CMD:=/bin/sed} 's/\([a-z]\)\+_\([a-z0-9]\+\)/\2/'`
  $MAS_LOGGER "1. MAS_PNAME=$MAS_PNAME"
  export MAS_PSET_NAME=`echo $MAS_STY_TAIL | ${MAS_SED_CMD:=/bin/sed} 's/\([a-z]\+\)_\([a-z0-9]\+\)/\1/'`
  $MAS_LOGGER "1. MAS_PSET_NAME=$MAS_PSET_NAME"
export MAS_RSC="$MAS_RSC;screen_bash:$LINENO($STY)"
  if [ -z "$MAS_PNAME" ] ; then
    MAS_PSET_NAME=$MAS_STY_TAIL
    $MAS_LOGGER "2. MAS_PNAME=$MAS_PNAME"
    MAS_PNAME=default
    $MAS_LOGGER "2. MAS_PSET_NAME=$MAS_PSET_NAME"
  fi
echo "sb.$$.$LINENO ($STY) date:`date +'%s.%N'`" >>"/tmp/mscreen.log"
  
#   if [ -n "$MAS_PROFILE_GROUPS" ] ; then
#     if [ -d "$MAS_PROFILE_GROUPS" ] ; then
#       if [ -n "$MAS_PSET_NAME" ] ; then
#         ( echo "L$LINENO" >&2 && sleep 1 )
#         export MAS_PROFILE_GROUP="$MAS_PROFILE_GROUPS/$MAS_PSET_NAME"
#         [[ -d "$MAS_PROFILE_GROUP" ]] || ( mkdir $MAS_PROFILE_GROUP && echo "Created d pg:'$MAS_PROFILE_GROUP'" >&2  && sleep 1 )
#         [[ -n "$MAS_PNAME" ]]     && export MAS_GROUPRC="$MAS_PROFILE_GROUP/$MAS_PNAME"
#         if [ -n "$MAS_GROUPRC" ] ; then
#           [[ -r "$MAS_GROUPRC" ]] || ( cp "$MAS_PROFILE_GROUPS/template/default" $MAS_GROUPRC && echo "Created f grc:'$MAS_GROUPRC/default'" >&2  && sleep 1 )
#         fi
#         ( echo "L$LINENO" >&2 && sleep 1 )
#       fi
#       ( echo "L$LINENO" >&2 && sleep 1 )
#     fi
#     ( echo "L$LINENO" >&2 && sleep 1 )
#   fi
  #echo ". $MAS_PROFILE_GROUPS/..." >&2
  #echo "B0: $MAS_PROFILE_GROUP : $MAS_GROUPRC" >&2
  echo "init ($STY) date:`date +'%s.%N'`" >>"/tmp/mscreen.log"
  [[ -r $MAS_PROFILE_GROUPS/bin/init.sh ]] && . $MAS_PROFILE_GROUPS/bin/init.sh && echo "INIT $MAS_GROUPRC" >&2
  #echo "B1: $MAS_PROFILE_GROUP : $MAS_GROUPRC" >&2
  export MAS_RSC="$MAS_RSC;screen_bash:$LINENO($STY)"

  [[ -n $MAS_PROFILE_DATA_DIR && -d $MAS_PROFILE_DATA_DIR && -f $MAS_PROFILE_DATA_DIR/oldpwd.txt ]] && ${MAS_CAT_CMD:=/bin/cat} $MAS_PROFILE_DATA_DIR/oldpwd.txt
  [[ -n $MAS_PROFILE_DATA_DIR && -d $MAS_PROFILE_DATA_DIR && -f $MAS_PROFILE_DATA_DIR/pwd.txt ]] && ${MAS_CAT_CMD:=/bin/cat} $MAS_PROFILE_DATA_DIR/pwd.txt
  $MAS_LOGGER "MAS_GROUPRC:$MAS_GROUPRC"
  if [ -n "$MAS_GROUPRC" -a -r "$MAS_GROUPRC" ] ; then
#    echo "A bash --rcfile \"$MAS_GROUPRC\" $@"
#    sleep 3
export MAS_RSC="$MAS_RSC;screen_bash:$LINENO($STY:$MAS_GROUPRC)"
  echo "bash1 ($STY) date:`date +'%s.%N'`" >>"/tmp/mscreen.log"
    exec bash --rcfile "$MAS_GROUPRC" "$@"
#    echo "B bash --rcfile \"$MAS_GROUPRC\""
#    sleep 3
  else
  echo "bash2 ($STY) date:`date +'%s.%N'`" >>"/tmp/mscreen.log"
    echo "bash $@"
    exec bash "$@"
  fi
else
  $MAS_LOGGER "STY Not set"
  echo "STY Not set" >/dev/stderr
fi
export MAS_RSC="$MAS_RSC;screen_bash:$LINENO($STY)"
